set_fan_speed_tracked_state:
  target:
    entity:
      integration: bond_pro
      domain: fan
  fields:
    speed:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_switch_power_tracked_state:
  target:
    entity:
      integration: bond_pro
      domain: switch
  fields:
    power_state:
      required: true
      selector:
        boolean:

set_light_power_tracked_state:
  target:
    entity:
      integration: bond_pro
      domain: light
  fields:
    power_state:
      required: true
      selector:
        boolean:

set_light_brightness_tracked_state:
  target:
    entity:
      integration: bond_pro
      domain: light
  fields:
    brightness:
      required: true
      selector:
        number:
          min: 0
          max: 255

rf_scan:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: bond_pro

transmit_command:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: bond_pro
    device_id:
      required: true
      selector:
        text:
    command_id:
      required: true
      selector:
        text:

reload_device:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    device_id:
      required: true
      selector:
        text:

list_skeds:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    target_type:
      required: true
      selector:
        select:
          options: [device, group, scene, channel]
    target_id:
      required: true
      selector:
        text:

create_sked:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    target_type:
      required: true
      selector:
        select:
          options: [device, group, scene, channel]
    target_id:
      required: true
      selector:
        text:
    enabled:
      selector:
        boolean:
    action:
      selector:
        text:
    argument:
      selector:
        object:
    seconds:
      selector:
        number:
          min: -86400
          max: 86400
          unit_of_measurement: s
    days_of_week:
      selector:
        object:
    mark:
      selector:
        select:
          options: [midnight, sunrise, sunset, dawn, dusk]

update_sked:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    target_type:
      required: true
      selector:
        select:
          options: [device, group, scene, channel]
    target_id:
      required: true
      selector:
        text:
    sked_id:
      required: true
      selector:
        text:
    enabled:
      selector:
        boolean:
    action:
      selector:
        text:
    argument:
      selector:
        object:
    seconds:
      selector:
        number:
          min: -86400
          max: 86400
          unit_of_measurement: s
    days_of_week:
      selector:
        object:
    mark:
      selector:
        select:
          options: [midnight, sunrise, sunset, dawn, dusk]

delete_sked:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    target_type:
      required: true
      selector:
        select:
          options: [device, group, scene, channel]
    target_id:
      required: true
      selector:
        text:
    sked_id:
      required: true
      selector:
        text:

channel_action:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: bond_pro
    channel_id:
      required: true
      selector:
        text:
    action:
      required: true
      selector:
        text:
    argument:
      selector:
        object:
